#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

print_rec() {
	echo $1 | awk -v sub_d=$2 '{split($0, a); print "The subdomain", sub_d, "is a", a[7], "record and points to", a[8]}'
}

sub_domains=('www' 'lb-01' 'web-01' 'web-02')

if [ -z "$2" ]
then
	for sub_domain in "${sub_domains[@]}"
	do
		match=$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION:')
		print_rec "$match" "$sub_domain"
	done
else
	match=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:')
	print_rec "$match" "$2"
fi
