#!/usr/bin/env bash
# $1 -> PATH_TO_FILE
# $2 -> IP
# $3 -> USERNAME
# $4 -> PATH_TO_SSH_KEY

if [ -z "$3" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:"
fi
