#!/usr/bin/env bash
# Install nginx and add default index.html

apt-get -y update
apt-get -y install nginx
echo "Holberton School rules!" > /var/www/html/index.nginx-debian.html
service nginx restart
