#!/usr/bin/env bash
# Install nginx and add default index.html

sudo get -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
