#!/usr/bin/env bash

apt-get -y update
apt-get -y install nginx

echo Holberton School > /var/www/html/index.html

directive=`cat /etc/nginx/sites-enabled/default | grep "rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"`
if [ -z "$directive" ]
then
	directive="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
	old="root /var/www/html;"
	redirect="$old\n\n\t$directive"
	sed -i "s|$old|$redirect|" /etc/nginx/sites-enabled/default
fi

service nginx restart
