#!/usr/bin/env bash
# Adds a default 404 page

apt-get -y update
apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page
" > /var/www/html/404.html

directive=$(grep "rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default)
if [ -z "$directive" ]
then
	directive="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
	old="root /var/www/html;"
	redirect="$old\n\n\t$directive"
	sed -i "s|$old|$redirect|" /etc/nginx/sites-enabled/default
fi

error=$(grep "error_page 404 = /404.html;" /etc/nginx/sites-enabled/default)
if [ -z "$error" ]
then
	echo "error_page 404 = /404.html;" >> /etc/nginx/sites-enabled/default
fi

service nginx restart
