#!/usr/bin/env bash
# Install and configure HAproxy

apt -y update
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo -e "\nbackend web-backend" >> /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver  2527-web-01 35.231.129.240:80 check" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver  2527-web-02 35.196.6.217:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
