#!/usr/bin/env bash
# Prints 'To infinity and beyond' forever

echo "$$" > /var/run/holbertonscript.pid

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm -rf /var/run/holbertonscript.pid" SIGQUIT SIGTERM
done
