#!/usr/bin/env bash
# Prints "Holberton School" 10 times using while loop to stdout

while read -r line
do
	IFS=':'
	read -ra ARY <<< "$line"
	echo "The user ${ARY[0]} is part of the ${ARY[3]} gang, lives in ${ARY[5]} and rides ${ARY[6]}. ${ARY[2]}'s place is protected by the passcode ${ARY[1]}, more info about the user here: ${ARY[4]}"
done < /etc/passwd
