#!/usr/bin/env bash
# Prints "Holberton School" 10 times using while loop to stdout

h=0
while [[ $h -le 12 ]]
do
	echo "Hours: $h"
		m=1
		while [[ $m -le 59 ]] 
		do
			echo "$m"
			((m++))
		done
	((h++))
done
