#!/usr/bin/env bash
# Prints "Holberton School" 10 times to stdout

FILE="holbertonschool"
if test -e "$FILE"
then
	echo "$FILE file exists"
	if [ -s $FILE ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	if test -f "$FILE"
	then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
