#!/usr/bin/env bash
# configures an Ubuntu server within a docker container
sudo cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1 localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i '1i8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
